"""
Django settings for stubble_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-hb1o*=wufg+k@qbl#f4a$ugu@#zp0su(qz!n8*5452&im_50be',
)

# --- Google Earth Engine ---
GEE_PROJECT_ID = os.environ.get('GEE_PROJECT_ID', '')
GEE_SERVICE_ACCOUNT_EMAIL = os.environ.get('GEE_SERVICE_ACCOUNT_EMAIL', '')
GEE_KEY_FILE_PATH = os.environ.get('GEE_KEY_FILE_PATH', str(BASE_DIR / 'gee-service-account-key.json'))
GEE_OAUTH_CREDENTIALS_PATH = os.environ.get('GEE_OAUTH_CREDENTIALS_PATH', str(BASE_DIR / 'credentials.json'))
GEE_OAUTH_TOKEN_PATH = os.environ.get('GEE_OAUTH_TOKEN_PATH', str(BASE_DIR / 'token.json'))
GEE_DRIVE_EXPORT_FOLDER = os.environ.get('GEE_DRIVE_EXPORT_FOLDER', 'GEE_Exports')
GEE_RICE_MASK_ASSET_ID = os.environ.get(
    'GEE_RICE_MASK_ASSET_ID',
    f'projects/{GEE_PROJECT_ID}/assets/rice_mask_hafizabad_v1' if GEE_PROJECT_ID else '',
)
GEE_DSS_TRAINING_TABLE_ASSET_ID = os.environ.get(
    'GEE_DSS_TRAINING_TABLE_ASSET_ID',
    f'projects/{GEE_PROJECT_ID}/assets/dss_training_table_hafizabad_v1' if GEE_PROJECT_ID else '',
)
FIRE_LOOKBACK_DAYS = int(os.environ.get('FIRE_LOOKBACK_DAYS', '3'))

# --- Google Cloud Storage (tile persistence) ---
GCS_BUCKET_NAME = os.environ.get('GCS_BUCKET_NAME', '')
GCS_TILES_PREFIX = 'imgs_pak_punjab'
GCS_STAGE_TILES_PREFIX = 'stage_tiles'

# --- Shared secret for Cloud Scheduler-triggered endpoints ---
CLOUD_SCHEDULER_TOKEN = os.environ.get('CLOUD_SCHEDULER_TOKEN', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Cloud Run terminates TLS upstream and forwards over plain HTTP with this header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    origin for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if origin
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'corsheaders',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fires',
    'rest_framework',
]

CORS_ALLOWED_ORIGINS = os.environ.get(
    'DJANGO_CORS_ALLOWED_ORIGINS', 'http://localhost:3000'
).split(',')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'django-static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = []

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Tile image serving
MEDIA_URL = '/tiles/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'imgs_pak_punjab')  # adjust if your folder has a different name