# Generated by Django 5.2.5 on 2025-08-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(max_length=100, unique=True)),
                ('fire_date', models.DateTimeField(blank=True, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('province', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['point_id'], name='fires_firep_point_i_5074c1_idx'), models.Index(fields=['longitude', 'latitude'], name='fires_firep_longitu_901f69_idx')],
            },
        ),
        migrations.CreateModel(
            name='FireObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_date', models.DateTimeField()),
                ('NDVI', models.FloatField(blank=True, null=True)),
                ('NDWI', models.FloatField(blank=True, null=True)),
                ('NBR', models.FloatField(blank=True, null=True)),
                ('NDRE', models.FloatField(blank=True, null=True)),
                ('VV', models.FloatField(blank=True, null=True)),
                ('VH', models.FloatField(blank=True, null=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obs', to='fires.firepoint')),
            ],
            options={
                'indexes': [models.Index(fields=['image_date'], name='fires_fireo_image_d_d173aa_idx')],
                'unique_together': {('point', 'image_date')},
            },
        ),
    ]
