# Generated by Django 5.2.7 on 2026-08-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0002_stagetiledate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiceAreaEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectares', models.FloatField()),
                ('season_year', models.IntegerField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.AddField(
            model_name='stagetiledate',
            name='dominant_stage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagetiledate',
            name='stage_pixel_counts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
