# backend/fires/pdf_report.py
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_LEFT
from datetime import datetime

from .geocode_utils import get_province_city  # OpenCage helper

def generate_fire_pdf(fire_point, history_counts):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=30)
    elements = []

    styles = getSampleStyleSheet()
    # Custom Title Style (white on red background)
    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=18,
        textColor=colors.white,
        alignment=TA_LEFT,
        spaceAfter=14
    )

    # Section heading style
    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=colors.black,
        spaceBefore=15,
        spaceAfter=8
    )

    # Normal cell text
    normal_style = styles["Normal"]
    normal_style.fontSize = 10

    # 🔥 HEADER BAR
    elements.append(
        Table(
            [[Paragraph("■ Fire Incident Report", title_style)]],
            colWidths=[450],
            style=[
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#8B0000")),
                ("BOX", (0, 0), (-1, -1), 0, colors.white),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(Spacer(1, 15))

    # 🧭 Location data via OpenCage
    province, city, nearby_location = get_province_city(fire_point.latitude, fire_point.longitude)
    # 🧭 Location data via OpenCage
    province, city, nearby_location = get_province_city(fire_point.latitude, fire_point.longitude)

    google_maps_link = f"<link href='https://www.google.com/maps?q={fire_point.latitude},{fire_point.longitude}'>View on Google Maps</link>"
    # 📊 FIRE DETAILS TABLE
    details_data = [
        ["Point ID:", fire_point.point_id],
        ["Latitude:", f"{fire_point.latitude:.6f}"],
        ["Longitude:", f"{fire_point.longitude:.6f}"],
        ["Fire Date:", fire_point.fire_date.strftime("%Y-%m-%d") if fire_point.fire_date else "N/A"],
        ["Province:", province],
        ["City:", city],
        ["Google Maps:", google_maps_link],
        ["Nearby Location:", nearby_location],
    ]
    details_table = Table(details_data, colWidths=[110, 370])
    details_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.whitesmoke),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.whitesmoke]),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#8B0000")),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.lightgrey),
    ]))
    elements.append(details_table)

    # 📌 FIRE HISTORY SECTION
    elements.append(Paragraph("■ Fire History Overview", section_heading))

    history_data = [
        ["Nearby Fires (last 7 days):", str(history_counts.get('7_days', 0))],
        ["Seasonal Fires (10 km radius):", str(history_counts.get('seasonal', 0))],
    ]

    history_table = Table(history_data, colWidths=[200, 280])
    history_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.whitesmoke),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.whitesmoke]),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#8B0000")),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(history_table)
    elements.append(Spacer(1, 25))

    # FOOTER
    footer_text = "<i>This report was automatically generated by the Fire Monitoring Dashboard.</i>"
    elements.append(Paragraph(footer_text, normal_style))

    # ✅ Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer
